### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ahmedezz26** [paveldat/gesture_volume_control_v2#1]
Hey!
 I just wanted to ask you about the newly added box at V2 is limits the hand taking the control? 
by my question I mean if another hand was inside the frame but outside the original (first) controlling hand would it be detected or not?
Thank you!

**Comment by paveldat** [comment]
Hello!
Control will be carried out by the first hand found in the frame. I mean, if from the very beginning you control with your right hand and bring your left hand into the frame, then the control will take place on the right hand, but if you remove the right hand from the frame, leaving the left, then control will go to the left hand.
To learn more, you can clone my repository and test.
Good luck!

**Comment by ahmedezz26** [comment]
perfect!
Thank you.

**Comment by paveldat** [comment]
👍
